#!/bin/bash

SSID=$1

if [[ -z $SSID ]]; then
    echo Usage: $0 SSID
    exit 1
fi

trap exit INT TERM

wait_disconnect() {
    while :; do
        arping -I wlan0 -f -w 5 10.42.0.1 || break
        sleep 15s
    done
}

wait_ssid() {
    iwconfig wlan0 essid off

    while :; do
        sleep 5s
        iwlist wlan0 scan | grep "\"$SSID\"" && break
    done

    iwconfig wlan0 essid "$SSID" channel 1
}

ip link set wlan0 down
iwconfig wlan0 mode ad-hoc
ip link set wlan0 up

while :; do
    wait_ssid || continue
    sleep 10s
    adhocd.up 2>/dev/null
    wait_disconnect || continue
done
