#!/usr/bin/python3

import atsci
import sys
import time

STABILIZE_SECS = 30

def calibrate(cmd, cond):
    print("place sensor in {} solution".format(cond))
    input("press enter when ready")

    print("calibrating for {}...".format(cond), end="")
    sensor.write("{},{}".format(cmd, cond))
    print("done")

try:
    probe = sys.argv[1]
    low = sys.argv[2]
    high = sys.argv[3]
except IndexError:
    print("Usage {} PROBE-K-VALUE LOW-SOLUTION HIGH-SOLUTION".format(
        sys.argv[0]))
    sys.exit(1)

with atsci.AtSciSensor() as sensor:
    print("letting temperature stabilize for {} second(s)".format(
        STABILIZE_SECS))
    sensor.switch(atsci.TEMP)
    sensor.write("C")

    start = time.time()

    while True:
        elapsed = time.time() - start

        if elapsed > STABILIZE_SECS:
            break;

        print("{:3}s: {}C".format(int(elapsed), float(sensor.read())))
        time.sleep(1)

    sensor.write("E")
    temp = float(sensor.ask("R"))

    # Leave continuous mode and clear calibration.
    sensor.switch(atsci.COND)
    sensor.write("C,0")
    sensor.write("Cal,clear");

    print("using probe {}".format(probe))
    sensor.write("K,{}".format(probe))

    print("adjusting temperature to {}°C".format(temp))
    sensor.write("T,{:.3}".format(temp))

    # calibrate for dry sensor.
    print("make sure the sensor is dry")
    input("press enter when ready")
    sensor.write("Cal,dry")

    calibrate("Cal,low", low)
    calibrate("Cal,high", high)
