#!/bin/bash

SSID=$1

if [[ -z $SSID ]]; then
    echo Usage: $0 SSID
    exit 1
fi

# Make sure the interface is up.
ip link set wlan0 up
# Join the SSID on channel 1.
iwconfig wlan0 mode ad-hoc essid "$SSID" channel 1
