#!/usr/bin/bash

if [[ $# -lt 1 ]]; then
    echo Usage: $0 SLEEP-TIME
    echo
    echo For example, to take a reading every 15 minutes, run
    echo $0 15m

    exit 1
fi

trap exit 0 INT

while true; do
    dtnsend -s dtn://pi.dtn -d dtn://yellow.dtn -t m -p "$(read-sensors)" \
        -e 5184000
    sleep "$1"
done
