#!/usr/bin/python3

import atsci
import datetime

with atsci.AtSciSensor() as sensor:
    sensor.switch(atsci.TEMP)
    temp = float(sensor.ask("R"))

    sensor.switch(atsci.COND)
    sensor.write("T,{:.3f}".format(temp))
    [cond, tds, sal, sg] = (float(x) for x in sensor.ask("R").split(b","))

    sensor.switch(atsci.PH)
    sensor.write("T,{:.3f}".format(temp))
    ph = float(sensor.ask("R"))

    now = datetime.datetime.utcnow()
    print("{}\t{}\t{}\t{}".format(now, temp, cond, ph))
