#!/usr/bin/python3

import sys

from dtnsense import atsci

BOARDS = {
    "temp": atsci.TEMP,
    "cond": atsci.COND,
    "ph": atsci.PH,
}

board = BOARDS[sys.argv[1]]
cmd = sys.argv[2]

with atsci.AtSciSensor() as sensor:
    sensor.switch(board)
    print(sensor.ask(cmd).decode("ascii"))
