#!/bin/bash

SSID=$1

if [[ -z $SSID ]]; then
    echo Usage: $0 SSID
    exit 1
fi

coproc IW {
    iw event
}

trap exit INT TERM

while :; do
    wait-beacon "$SSID" || continue

    coproc WAIT {
        timeout 20 wait-line "new station"
    } <&${IW[0]}

    join-adhoc "$SSID" || continue
    wait -n || continue

    wait-disconnect
done
