#!/bin/bash

SSID=$1

if [[ -z $SSID ]]; then
    echo Usage: $0 SSID
    exit 1
fi

trap exit INT TERM

while :; do
    timeout 10s wait-beacon "$SSID" || continue
    join-adhoc "$SSID" || continue
    wait-disconnect || continue
done
