#!/bin/bash

SSID=$1

if [[ -z $SSID ]]; then
    echo Usage: $0 SSID
    exit 1
fi

# Create the monitor interface and bring it up.
iw dev wlan0 interface add mon0 type monitor
ip link set mon0 up

# Wait for the first beacon frame from the given SSID.
while read line; do
    [[ $line =~ "($SSID)" ]] && break;
done < <(tcpdump -l -i mon0 "(type mgt subtype beacon)" 2>/dev/null)

# Send tcpdump SIGPIPE manually, since it may not get it from loop breaking.
pkill -PIPE -P $!

# Shut down the monitor and delete it.
ip link set mon0 down
iw dev mon0 del
