#!/bin/bash

SSID=$1

if [[ -z $SSID ]]; then
    echo Usage: $0 SSID
    exit 1
fi

# Consider beacon frames from the given SSID.
FILTER="wlan.fc.subtype == 8 && wlan_mgt.ssid == \"$SSID\""

# Create the monitor interface and bring it up.
iw dev wlan0 interface add mon0 type monitor
ip link set mon0 up

# Wait for the first matching frame.
sudo -u "#$SUDO_UID" tshark -i mon0 -l -Y "$FILTER" | head -1 >/dev/null

# Shut down the monitor and delete it.
ip link set mon0 down
iw dev mon0 del
